<?php echo $this->doctype() ?>
<html>
<head>
  <meta charset="UTF-8" />
    
  <!-- Page Title -->
  <?php echo $this->headTitle() ?>
    
  <!-- CSS & other <link> elements defined on the Bootstrap -->
  <?php echo $this->headLink() ?>
</head>
<body>
  <header>
    <h1>Zend Music Collection</h1>
    
    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
    <!-- This section is only displayed if the user is logged in -->
    <p id="user">
      Welcome, <?php echo Zend_Auth::getInstance()->getIdentity() ?> | 
      <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')) ?>">Logout</a>
    </p>
    <?php endif ?>
  </header>

  <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
  <nav>
    <?php echo $this->navigation()->menu()->setUlClass('dropdown dropdown-horizontal menu_princ'); ?>
  </nav>
  <?php endif ?>

  <section>
    <p id="breadcrumbs">
    		<?php echo $this->navigation()->breadcrumbs()->setRenderInvisible(true)->setSeparator(" &raquo; ") ?>
    </p>
    
    <?php if (isset($this->messages) && count($this->messages) > 0): foreach ($this->messages as $message): ?>
    <!-- Application Messages -->
    <p><?php echo $message ?></p> 
    <?php endforeach; endif; ?>
      
    <!-- View Content -->
    <?php echo $this->layout()->content ?>
  </section>
  
  <footer>
    Zend Music Collection<br/>
    This work is licensed under the <a href="http://www.gnu.org/licenses/gpl-2.0.html">GNU General Public License V2</a>.
  </footer>
    
  <!-- Javascripts defined on the Bootstrap -->
  <?php echo $this->headScript() ?>
</body>
</html>
