<?php echo $this->doctype() ?>
<html>
<head>
    <meta charset="UTF-8" />
    
    <!-- Page Title -->
    <?php echo $this->headTitle() ?>
    
    <!-- CSS & other <link> elements defined on the Bootstrap -->
    <?php echo $this->headLink() ?>
</head>
<body>
    <header>
        <h1>Music Collection</h1>
    </header>

    <section>
        <?php if (isset($this->messages) && count($this->messages) > 0): foreach ($this->messages as $message): ?>
        <!-- Application Messages -->
        <p><?php echo $message ?></p> 
        <?php endforeach; endif; ?>
            
        <!-- View Content -->
        
        <?php echo $this->layout()->content ?>
    </section>
    
    <footer>
        <p>This could be the footer! :)</p>
    </footer>
    
    <!-- Javascripts defined on the Bootstrap -->
    <?php echo $this->headScript() ?>
</body>
</html>
