<?php if ($this->pageCount): ?>
<span>
  Showing <?php echo $this->firstItemNumber ?> - <?php echo $this->lastItemNumber ?> 
  of <?php echo $this->totalItemCount ?>
</span> 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">First</a> |
<?php endif ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a> |
<?php endif ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">Next &gt;</a> |
<?php endif ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">Last</a>
<?php endif ?>
<?php endif ?>