<h2>Albums</h2>

<?php if ($this->paginator): ?>
<table summary="Albums">
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
    	<!-- This sets up the pagination controls partial -->
      <td><?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml') ?></td>
    </tr>
  </tfoot>
  <tbody>
    <?php if ($this->paginator->getTotalItemCount() == 0): ?>
    <tr>
      <td>No album found.</td>
    </tr>
    <?php else: foreach ($this->paginator as $album): $artist = $album->findParentRow('Model_Artist') ?>
    <tr>
      <td>
        <a href="<?php echo $this->url(array('action' => 'show', 'id' => $album->id)) ?>">
          <?php echo $album->name ?>
        </a>
      </td>
      <td>
        <a href="<?php echo $this->url(array('controller' => 'artists', 'action' => 'show', 'id' => $artist->id)) ?>">
          <?php echo $artist->name ?>
        </a>
      </td>
    </tr>
    <?php  endforeach; endif ?>
  </tbody>
</table>
<?php endif ?>

<p><a href="<?php echo $this->url(array('action' => 'new')) ?>">New Album</a></p>